name: Generate GitHub Metrics

on:
  schedule:
    # Runs daily at 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: RNAGIT
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_achievements: yes
          plugin_achievements_threshold: A
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_contributors: yes
          plugin_contributors_authorized: RNAGIT
          plugin_discussions: yes
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_charts: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_recent_categories: markup, programming
          plugin_languages_threshold: 0%
          plugin_licenses: yes
          plugin_licenses_legal: yes
          plugin_licenses_conclusion: table
          plugin_lines: yes
          plugin_notable: yes
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_types: followers, following
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_desktop: yes
          plugin_pagespeed_mobile: yes
          plugin_reactions: yes
          plugin_skyline: yes
          plugin_skyline_year: current
          plugin_stargazers: yes
          plugin_stars_limit: 4
          plugin_stars_query: language:python
          plugin_stars_recent: yes
          plugin_traffic: yes
          plugin_traffic_days: 14
          output: github-metrics.svg

      - name: Commit metrics
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update GitHub metrics"
          file_pattern: github-metrics.svg

